query_map = {
    "Cafés": "cafes",
    "Bakeries": "bakeries",
    "Fast Food": "fast+food",
    "Ice Cream Shops": "ice+cream+shops",
    "Bars": "bars",
    "Hotels": "hotels",
    "Motels": "motels",
    "Bed & Breakfasts": "bed+and+breakfasts",
    "Resorts": "resorts",
    "Malls": "malls",
    "Shopping Centers": "shopping+centers",
    "Clothing Stores": "clothing+stores",
    "Electronics Stores": "electronics+stores",
    "Supermarkets": "supermarkets",
    "Bookstores": "bookstores",
    "Pharmacies": "pharmacies",
    "Clinics": "clinics",
    "Dentists": "dentists",
    "Veterinary Clinics": "veterinary+clinics",
    "Airports": "airports",
    "Car Rentals": "car+rentals",
    "Gas Stations": "gas+stations",
    "Taxi Services": "taxi+services",
    "Bus Stations": "bus+stations",
    "Train Stations": "train+stations",
    "Cinemas": "cinemas",
    "Theaters": "theaters",
    "Museums": "museums",
    "Parks": "parks",
    "Sports Venues": "sports+venues",
    "Amusement Parks": "amusement+parks",
    "Schools": "schools",
    "Universities": "universities",
    "Libraries": "libraries",
    "Training Centers": "training+centers",
    "Government Offices": "government+offices",
    "Post Offices": "post+offices",
    "Police Stations": "police+stations",
    "Fire Stations": "fire+stations",
    "ATMs": "atms",
    "Banks": "banks",
    "Fitness Centers": "fitness+centers",
    "Beauty Salons": "beauty+salons",
    "Real Estate Agencies": "real+estate+agencies",
    "Dry Cleaners": "dry+cleaners"
}


icons_map = {
    "Cafés": "fa-coffee",
    "Bakeries": "fa-bread-slice",
    "Fast Food": "fa-hamburger",
    "Ice Cream Shops": "fa-ice-cream",
    "Bars": "fa-glass",
    "Hotels": "fa-hotel",
    "Motels": "fa-bed",
    "Bed & Breakfasts": "fa-bed",
    "Resorts": "fa-sun",
    "Malls": "fa-store",
    "Shopping Centers": "fa-store",
    "Clothing Stores": "fa-tshirt",
    "Electronics Stores": "fa-laptop",
    "Supermarkets": "fa-store-alt",
    "Bookstores": "fa-book",
    "Pharmacies": "fa-medkit",
    "Clinics": "fa-clinic-medical",
    "Dentists": "fa-tooth",
    "Veterinary Clinics": "fa-paw",
    "Airports": "fa-airplane-departure",
    "Car Rentals": "fa-car",
    "Gas Stations": "fa-gas-pump",
    "Taxi Services": "fa-taxi",
    "Bus Stations": "fa-bus",
    "Train Stations": "fa-train",
    "Cinemas": "fa-film",
    "Theaters": "fa-theater-masks",
    "Museums": "fa-university",
    "Parks": "fa-tree",
    "Sports Venues": "fa-futbol",
    "Amusement Parks": "fa-roller-coaster",
    "Schools": "fa-school",
    "Universities": "fa-university",
    "Libraries": "fa-book",
    "Training Centers": "fa-chalkboard-teacher",
    "Government Offices": "fa-building",
    "Post Offices": "fa-mail-bulk",
    "Police Stations": "fa-police",
    "Fire Stations": "fa-fire",
    "ATMs": "fa-credit-card",
    "Banks": "fa-university",
    "Fitness Centers": "fa-dumbbell",
    "Beauty Salons": "fa-cut",
    "Real Estate Agencies": "fa-house-user",
    "Dry Cleaners": "fa-tshirt"
}
